### ISSUE TITLE
没有反应

### ISSUE THREAD

**Issue by cgw2023** [RenYuan-MC/QuickShopForm#2]
QuickShop-Hikari-6.2.0.7 (自行建构)
QuickShopForm 5243b2a
floodgate-spigot
folia-bundler-1.21.1-R0.1-SNAPSHOT-mojmap
Geyser-Velocity

左键右键点击QS商店都是没有任何介面弹出，是我用法不当还是有问题

**Comment by lRENyaaa** [comment]
这么奇怪？有更多相关信息吗

**Comment by lRENyaaa** [comment]
未能复现成功
![image](https://github.com/user-attachments/assets/7d798783-06a9-4001-9e06-da7b4dde580f)
注: 空商店是不弹菜单的
